### ISSUE TITLE
Use better tooltips

### ISSUE THREAD

**Issue by GaryJones** [christophercochran/Genesis-Visual-Hook-Guide#12]
Browser tooltips that originate from title text are some what inaccessible to certain user agents - i.e. text-to-speech browsers will often not read them out.

Instead of adding it as a `title` attribute, consider:
- adding it inline: `<span class="screen-reader-text tooltip">Description goes here</span>
- adding an internal style sheet that applies a screen reader text class to visually hide the content.
- adding a script reference and internal style sheet that visually display tooltips on hover, a la Bootstrap.

It's more work, but would greatly improve the accessibility of the plugin in one aspect.

cc @RRWD @amandarush

**Comment by RRWD** [comment]
Agree with @GaryJones. But it's not only useful for users of screen readers, people how use a touch device like a table don't see it either. But then again, who develops a site on an iPad. 
What about toggling the description in a show/hide span, triggered on click or on enter?

**Comment by amandarush** [comment]
If using the second method, you could borrow the screen reader text class
from WordPress core.







*From:* Gary Jones [mailto:notifications@github.com]
*Sent:* Wednesday, December 31, 2014 10:11 PM
*To:* christophercochran/Genesis-Visual-Hook-Guide
*Cc:* Amanda Rush
*Subject:* [Genesis-Visual-Hook-Guide] Use better tooltips (#12)



Browser tooltips that originate from title text are some what inaccessible
to certain user agents - i.e. text-to-speech browsers will often not read
them out.

Instead of adding it as a title attribute, consider:

   - adding it inline: `Description goes here
   - adding an internal style sheet that applies a screen reader text class
   to visually hide the content.
   - adding a script reference and internal style sheet that visually
   display tooltips on hover, a la Bootstrap.

It's more work, but would greatly improve the accessibility of the plugin
in one aspect.

cc @RRWD <https://github.com/RRWD> @amandarush
<https://github.com/amandarush>

—
Reply to this email directly or view it on GitHub
<https://github.com/christophercochran/Genesis-Visual-Hook-Guide/issues/12>.

**Comment by amandarush** [comment]
There’s also this example of accessible tooltips which may work with the
code as it currently stands:
http://accessibility.athena-ict.com/aria/examples/tooltip.shtml





*From:* Rian Rietveld [mailto:notifications@github.com]
*Sent:* Thursday, January 01, 2015 4:16 AM
*To:* christophercochran/Genesis-Visual-Hook-Guide
*Cc:* Amanda Rush
*Subject:* Re: [Genesis-Visual-Hook-Guide] Use better tooltips (#12)



Agree with @GaryJones <https://github.com/GaryJones>. But it's not only
useful for users of screen readers, people how use a touch device like a
table don't see it either. But then again, who develops a site on an iPad.
What about toggling the description in a show/hide span, triggered on click
or on enter?

—
Reply to this email directly or view it on GitHub
<https://github.com/christophercochran/Genesis-Visual-Hook-Guide/issues/12#issuecomment-68482981>
.

**Comment by christophercochran** [comment]
More work yes, but do think this is important.

This is great, thanks. Going to go over the different options, but I also like the idea of a toggle, even if it is used just as a visual cue. Could be as simple as a question mark beside the hook name that triggers the tooltip.

**Comment by RRWD** [comment]
Thanks :-)
