### ISSUE TITLE
Plugin deactivates when updating from 0.9.5 to 1.0.0

### ISSUE THREAD

**Issue by salcode** [christophercochran/Genesis-Visual-Hook-Guide#33]
This is a result of updating the filename from `g-hooks.php` to `genesis-visual-hook-guide.php`.

You can recreate this issue by checking out version `0.9.5`

```
$ git checkout 0.9.5
```

Activating the plugin at yoursite.com`/wp-admin/plugins.php?s=Genesis%20Visual%20Hook%20Guide&plugin_status=all`

then updating to version `1.0.0`

```
$ git checkout 1.0.0
```

While this seems trivial since Genesis Visual Hooks is so often turned on and off, I found it very disorienting when I made the update ( originally thinking there was something wrong with the plugin, until I was "smart" enough to check it was activated 😀 )

It is best practice  to use the same slug for the directory and plugin (see [Codex Writing a Plugin - Plugin Files](https://codex.wordpress.org/Writing_a_Plugin#Plugin_Files)) but due to the deactivation, I'd vote to going back to the original `g-hooks.php` as I don't see any drawback to it (other than not being quite as tidy)

**Comment by christophercochran** [comment]
Sadly, with this rolled out on the WordPress plugin repo as well, many have already auto updated, and will need to go through this again. 

Before releasing, I was little weary of this issue, but as you mentioned, this plugin is often or at least should be deactivated when not in use. It is a little annoyance, but because it is an actual release being 1.0.0, I was ok with this breaking change, to better adhere to the norm, and just tidy the plugin a little to keep organized as the plugin grows. 

Because the nature of the plugin, and no ill effect of the plugin being disabled to the usability/functionality of the site, and if changed again, anyone who updated already will need to go through the deactivation error again, I will leave as is. 

I will add a notice in the changelog on here about this, and have done so on the WordPress repo. But thank you for all your suggestions and PRs! I truly appreciate the care for the plugin you show.

**Comment by salcode** [comment]
Sounds good 👍
